CREATE SEQUENCE PROTOCOLO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_COLETA (
    PROTOCOLO INTEGER DEFAULT PROTOCOLO_SEQ.NEXTVAL NOT NULL,
    CEP VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    DT_AGENDAMENTO DATE NOT NULL,
    LIXO_RECICLAVEL CHAR(1) NOT NULL
    CONSTRAINT PK_TBL_COLETA PRIMARY KEY (PROTOCOLO)
);

-- Defina o valor padrão da coluna PROTOCOLO para o próximo valor da sequência
ALTER TABLE TBL_COLETA MODIFY (PROTOCOLO DEFAULT PROTOCOLO_SEQ.NEXTVAL);