CREATE SEQUENCE SEQ_USER
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_USERS (
    USER_ID INTEGER DEFAULT SEQ_USER.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    SENHA VARCHAR2(20) NOT NULL,
    ROLE VARCHAR2(50) DEFAULT 'USER'
);